chore(ci): Modify `refresh-instagram-access-token` action to use GitHub secrets

diff --git a/.github/actions/refresh-instagram-access-tokens/action.yml b/.github/actions/refresh-instagram-access-tokens/action.yml
--- a/.github/actions/refresh-instagram-access-tokens/action.yml
+++ b/.github/actions/refresh-instagram-access-tokens/action.yml
@@ -9,12 +9,6 @@ inputs:
     options:
       - staging
       - production
-  item_name:
-    description: '1Password item name containing the Instagram access token'
-    required: true
-  field_name:
-    description: '1Password field name containing the Instagram access token'
-    required: true
   token_cloud_ops_account:
     description: 'Cloud Ops account token'
     required: true
@@ -24,16 +18,26 @@ inputs:
 runs:
   using: 'composite'
   steps:
-    - name: Install 1Password CLI
-      uses: 1password/install-cli-action@v1
     - name: Refresh Instagram Access Tokens
+      id: refresh_tokens
       shell: bash
       env:
         BP_API_URL: ${{ inputs.environment == 'staging' && 'https://api.botpress.dev' || 'https://api.botpress.cloud' }}
         BP_WORKSPACE_ID: ${{ inputs.cloud_ops_workspace_id }}
         BP_TOKEN: ${{ inputs.token_cloud_ops_account }}
-        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
+        CURRENT_TOKEN: ${{ inputs.environment == 'staging' && secrets.STAGING_INSTAGRAM_ACCESS_TOKEN || secrets.PRODUCTION_INSTAGRAM_ACCESS_TOKEN }}
       run: |
-        script_path="./.github/scripts/refresh-instagram-access-tokens.sh"
-        chmod +x $script_path
-        $script_path "${{ inputs.item_name }}" "${{ inputs.field_name }}"
+        refresh_result=$(pnpm -F 'instagram' exec -- pnpm run --silent refreshTokens --json --instagramRefreshToken "$CURRENT_TOKEN")
+        new_token=$(echo "$refresh_result" | jq -r '.refreshedToken')
+        if [ -z "$new_token" ]; then
+          echo "❌ Error: Failed to refresh token" >&2
+          exit 1
+        fi
+
+        echo "$refresh_result" | jq -r '.message'
+        echo "✅ Tokens refreshed successfully"
+        echo "$new_token" >> "$GITHUB_OUTPUT"
+    - uses: ./.github/actions/create-or-update-secret
+      with:
+        secret_name: ${{ inputs.environment == 'staging' && 'STAGING_INSTAGRAM_ACCESS_TOKEN' || 'PRODUCTION_INSTAGRAM_ACCESS_TOKEN' }}
+        secret_value: ${{ steps.refresh_tokens.outputs.result }}
